### ISSUE TITLE
.gmy to .vtu converter error message

### ISSUE THREAD

**Issue by dhardma2** [hemelb-codes/hemelb#766]
Below is the error that I get using the gmy to vtu converter

python ~/hemelb-main/python-tools/hlb/converters/GmyUnstructuredGridReader.py filename

**Error message**

  File "/home/dhardma2/hemelb-main/python-tools/hlb/converters/GmyUnstructuredGridReader.py", line 18, in <module>
    from ..parsers.geometry.simple import ConfigLoader
ValueError: attempted relative import beyond top-level package

I tried changing the '..parsers' section to point to the 'simple.py' file, but it is then failing to read a .pyx file further downstream.

**Comment by rupertnash** [comment]
Is this now resolved? Please close if so! Ta

**Comment by seedel** [comment]
Thanks Rupert, I can get the .vtu file however then I am unable to use:` python -m hlb.converters.ExtractedPropertyUnstructuredGridReader ` without error. 

`ERROR: In /home/runner/work/vmtk-build/vmtk-build/vtk/Filters/Python/vtkPythonAlgorithm.cxx, line 112
vtkPythonAlgorithm (0x279a7e0): Failure when calling method: "ProcessRequest":

Traceback (most recent call last):
  File "/home/seede/gmy-tool/lib/python3.8/site-packages/vtkmodules/util/vtkAlgorithm.py", line 152, in ProcessRequest
    return vtkself.ProcessRequest(request, inInfo, outInfo)
  File "/home/seede/gmy-tool/lib/python3.8/site-packages/vtkmodules/util/vtkAlgorithm.py", line 198, in ProcessRequest
    return self.RequestData(request, inInfo, outInfo)
  File "/home/seede/gmy-tool/lib/python3.8/site-packages/hlb/converters/ExtractedPropertyUnstructuredGridReader.py", line 148, in RequestData
    self._CreateSkeleton(inp)
  File "/home/seede/gmy-tool/lib/python3.8/site-packages/hlb/converters/ExtractedPropertyUnstructuredGridReader.py", line 132, in _CreateSkeleton
    self.OutputCellIdsByInputIndex = MatchCorresponding(
  File "/home/seede/gmy-tool/lib/python3.8/site-packages/hlb/utils/utils.py", line 18, in MatchCorresponding
    assert first.shape == second.shape
AssertionError
ERROR: In /home/runner/work/vmtk-build/vmtk-build/vtk/Common/ExecutionModel/vtkExecutive.cxx, line 779
vtkCompositeDataPipeline (0x3104d70): Algorithm vtkPythonAlgorithm(0x279a7e0) returned failure for request: vtkInformation (0x3107320)
  Debug: Off
  Modified Time: 492
  Reference Count: 2
  Registered Events: (none)
  Request: REQUEST_DATA
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0
`

and ctrl-C doesn't work

**Comment by seedel** [comment]
That's them emailed over

**Comment by rupertnash** [comment]
Afraid I can't reproduce the error - I converted the geometry and the extraction data just fine:
```
python -m hlb.converters.GmyUnstructuredGridReader config.xml
python -m hlb.converters.ExtractedPropertyUnstructuredGridReader config.vtu wholegeometry-velocity.xtr 
```
Are you sure your installation of the python tools is up to date?

**Comment by rupertnash** [comment]
OK - so this was a tricky one. Unfortunately the VTK - python interface ends up swallowing all exceptions so the program keeps trying and ctrl-C just cancels one trip round the loop which makes it worse to understand.

This error is caused by you creating the config.vtu without using the XML config file. This means the `GmyUnstructuredGridReader` just creates its output in lattice units. Then the extracted property reader code will search for points in the output by position (which it gets correct because the xtr file includes those). For this particular case it finds exactly one point (instead of the expected 2.5 M) and gives up with the `AssertionError`.

The short term fix is to create the VTU skeleton using the XML input file rather than the bare GMY.
